# Generated by Django 3.0.7 on 2020-06-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0002_auto_20200610_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('dtColheita', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='comida',
            name='tipoComida',
        ),
        migrations.AlterField(
            model_name='comida',
            name='quantidade',
            field=models.PositiveIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='comida',
            name='valorCalorico',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AddField(
            model_name='comida',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comida.Tipo'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='opcoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comida.Opcoes'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='salada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comida.Salada'),
        ),
    ]
